### PR TITLE
Adds Nat Gateway resource support

### LINKED ISSUE #12: Adds NAT Gateway resource support
The NAT Gateway is already available through the web console, needs to add to terraform as well.

### PR DESCRIPTION
**Pull request by niuzhenguo**
Fixes #12

### CODE REVIEW

**Comment by antonin-a** [comment]
Hello,

This feature is highly waited by users, who can merge  ? 

Thanks you by advance !

**Comment by antonin-a** [comment]
@niuzhenguo thanks for you answer. If there is issue on plateform side we it's probably better to wait before merge, that will avoid error for TF provider users. Do you need some help on to resolve the WAF issue or it's already tracked ?

**Comment by niuzhenguo** [comment]
@antonin-a thanks, it's already tracked but seems still need some time to address that.

**Comment by antonin-a** [comment]
Hello @niuzhenguo, it seems to be ok on platform side now. Can you confirm ?

**Comment by antonin-a** [comment]
@niuzhenguo on my side I got a 401: 
`$ wget -O - https://nat.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/nat_gateways
--2018-07-13 07:50:19--  https://nat.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/nat_gateways
Resolving nat.eu-west-0.prod-cloud-ocb.orange-business.com (nat.eu-west-0.prod-cloud-ocb.orange-business.com)... 100.125.0.11
Connecting to nat.eu-west-0.prod-cloud-ocb.orange-business.com (nat.eu-west-0.prod-cloud-ocb.orange-business.com)|100.125.0.11|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.`

**Comment by niuzhenguo** [comment]
@antonin-a Just confirmed with the product team, my problem is because there's some special characters in my request header which doesn't pass the WAF rule. Will see if they can skip the requirement.

**Comment by antonin-a** [comment]
@niuzhenguo I just checked it with guy in charge of API testing, it's due to brackets on the user agent which causing WAF to block the request. We will fix this ASAP !

**Comment by niuzhenguo** [comment]
@antonin-a Thanks, it's OK now, merging this!

**Pull request merged**
